#!/bin/sh

if [ $# -ne 1 ]; then
  echo "usage: $0 <pid>" 2>&1
  exit 1
fi

if [ 0 -eq `echo $1 | awk '/^[1-9][0-9]*$/' | wc -c` ]; then
  echo "${1} isn't pid." 2>&1
  echo "usage: $0 <pid>" 2>&1
  exit 2
fi

if [ ! -e /proc/${1} ]; then
  echo "pid ${1} doesn't exist." 2>&1
  echo "usage: $0 <pid>" 2>&1
  exit 3
fi

